### PR TITLE
Read response from riemann when sending message over TCP

### PR DESCRIPTION
**Pull request by abailly**
This should fix issue #9 albeit without good test coverage...

### CODE REVIEW

**Comment by abailly** [comment]
Hi there,
Any plans to merge that/do a release in the near future? Alternatively, we (@Capital Match) could take over maintenance of the package if you want.

Cheers
Arnaud

**Comment by tel** [comment]
Hi there Arnaud,

First, I want to apologize for the absenteeism! This is an older project of which I've not had the opportunity to personally use in a while so it's tragically easy to fall behind.

Second, I'm happy to merge.

Third, if you guys at Capital Match are active users then I'd be more than happy to pass maintainership. I'm happy to see the project grow and I'm confident that I'm the largest blocker on it. I've begun by giving you a commit bit, but please let me know what you believe the best plans for moving things forward would be and we can discuss.

**Comment by tel** [comment]
I think in particular, next steps on maintainership after this merge include setting up for the next release. :)

**Comment by abailly** [comment]
Definitely something I want to do, as I currently maintain dependency in source :-) Yes we are actively using it and I plan to use it more, especially for querying. We are almost exclusively a Haskell shop and do a lot of thing with it but I like riemann and would keep on using it to aggregate all our logs, even if only to pass them down to some 3rd party for display/storage/analysis. But at least from our components perspective there is no dependency against external formats.

**Pull request merged**
